### ISSUE TITLE
Contradictory licensing

### ISSUE THREAD

**Issue by dann-merlin** [AndrielChaoti/starbound-lowhealthalarm#2]
Hey,

I am confused by your licensing.
The project is licensed under the MIT License,
but on the steam workshop page you state:
"You have my permission to alter this mod to suit your needs, but you do not have my permission to redistribute the mod in any form, original or altered."

This is contradictory to the MIT License which states:
Permission is hereby granted, [...], to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions.

Just a heads up. If you really feel the way you state on the steam page, you should not license this under the MIT license.

Cool mod anyways!

**Comment by AndrielChaoti** [comment]
good spot, i can fix that.
